name: cronparse
description: Parse and calculate different times related to Unix cron expressions
version: 0.1.1
homepage: https://github.com/justintout/cronparse

dev_dependencies: 
  test: ^1.3.4

environment:
  sdk: '>=2.12.0 <3.0.0'