name: cronparse
description: Parse and calculate different times related to Unix cron expressions
version: 0.2.0
homepage: https://github.com/justintout/cronparse

dev_dependencies:
  test: ^1.24.0

environment:
  sdk: ^3.0.0
